cameleon/Cargo.toml
cameleon/src/camera.rs
cameleon/src/lib.rs
cameleon/src/u3v/async_read.rs
cameleon/src/u3v/control_handle.rs
cameleon/src/u3v/mod.rs
cameleon/src/u3v/register_map.rs
cameleon/src/u3v/stream_handle.rs
device/src/u3v/mod.rs
gentl/src/imp/mod.rs

* Add some error kinds to `cameleon::StreamError` and `cameleon::ControlError`

Refactor streaming

---

README.md
cameleon/Cargo.toml
device/README.md
impl/Cargo.toml
impl/README.md

Edit manifest files

---

cameleon/README.md

Fix broken logo link

---

README.md
cameleon/Cargo.toml
cameleon/README.md

Change logo link

---

cameleon/examples/README.md
cameleon/examples/custom_ctxt.rs
cameleon/examples/params.rs
cameleon/examples/u3v/register_map.rs
cameleon/src/payload.rs

Refactor examples

---

README.md
cameleon/Cargo.toml
cameleon/README.md
cameleon/examples/README.md
cameleon/examples/stream.rs
cameleon/examples/u3v/README.md
cameleon/examples/u3v/register_map.rs
cameleon/src/camera.rs
cameleon/src/lib.rs
device/Cargo.toml

Bump version

---

cameleon/Cargo.toml
genapi/Cargo.toml

* Bump `cameleon-genapi` to 0.1.1
* Bump `cameleon` to 0.1.3
[cameleon] Update dependency on `cameleon-genapi`

Bump versions

---

README.md
cameleon/README.md
cameleon/src/lib.rs

Add libusb installation guide to README

---

genapi/src/formula.rs

fix #106 
- Formula parser now supports variable names matching special function names like "EXP" now (occured for several Point Grey camera GenICam xmls)

#106 Fix handling of variable names matching reserved function names

---

.github/workflows/ci.yml
test_all.sh

ref: https://github.com/cameleon-rs/cameleon/pull/107#issuecomment-876078888
None

Temporarily disable `clippy::default_numeric_fallback`

---

cameleon/src/genapi/mod.rs
device/src/u3v/protocol/cmd.rs
genapi/src/builder.rs
genapi/src/formula.rs
genapi/src/parser/elem_name.rs
genapi/src/parser/group.rs
genapi/src/parser/register_description.rs
genapi/src/parser/struct_reg.rs
genapi/src/register_base.rs
gentl/src/ffi/interface.rs
gentl/src/imp/device/u3v.rs
gentl/src/imp/interface/u3v.rs
gentl/src/imp/system/mod.rs

This should fix #115 . I was able to run 'test_all.sh' without any issues again.
Most of the changes are simple refactoring that don't change the program behavior in any way. 
Only in the case of the comment field (marked as dead code by Clippy) I had to make changes that may have an effect and adapt the corresponding test accordingly.
Fix errors shown by Clippy

Fix Clippy issues

---

device/Cargo.toml
device/src/u3v/device_builder.rs

Bump up rusb version to 0.9

---

cameleon/examples/gige/register_map.rs
genapi/src/parser/enumeration.rs
genapi/src/parser/node_base.rs

Make clippy satisfy

---

cameleon/src/u3v/control_handle.rs
genapi/src/enumeration.rs
genapi/src/string_reg.rs

Fix #124 
[cameleon] Fix building issue in Rust 1.58.0

Remove unneeded attributes

---

cameleon/Cargo.toml
device/Cargo.toml
genapi/Cargo.toml
impl/Cargo.toml
impl/macros/Cargo.toml

Release 0.1.4

---

README.md
cameleon/README.md
cameleon/src/lib.rs

Fix typo in README

---

genapi/src/utils.rs

In the `bytes_from_float()` function, when writing to a 32-bit float register, a buffer of length 4 would be passed to this function. But since the value passed is always an `f64`, the calls to `to_le_bytes()` and `to_be_bytes()` would always return a buffer size of 8, and attempting to wrote those 8 bytes to a 4 byte buffer results in a panic:
```
source slice length (8) does not match destination slice length (4)
```
* Fixed a bug where writing to 32-bit float registers would panic.

Fix the bytes_from_float() function and add a test for it

---

cameleon/Cargo.toml
device/Cargo.toml
genapi/Cargo.toml
impl/Cargo.toml
impl/macros/Cargo.toml

Bump up to 0.1.5

---

cameleon/Cargo.toml
device/Cargo.toml
genapi/Cargo.toml
impl/Cargo.toml
impl/macros/Cargo.toml

Bump to 0.1.6

---

genapi/src/masked_int_reg.rs
impl/macros/src/register_map.rs

Fix clippy 1.64 lints (unused parentheses)

---

cameleon/Cargo.toml
device/Cargo.toml
genapi/Cargo.toml
gentl/Cargo.toml
impl/Cargo.toml
impl/macros/Cargo.toml

I'll go ahead and insta-merge this to cut the release.

Bump versions to 0.1.10

---

cameleon/Cargo.toml
device/Cargo.toml
genapi/Cargo.toml
gentl/Cargo.toml
impl/Cargo.toml
impl/macros/Cargo.toml

Made using `cargo release version patch`.
Following the recipe in https://github.com/cameleon-rs/cameleon/issues/159#issuecomment-1473919709

Bump versions to 0.1.13

---

genapi/src/formula.rs

[chore] fix one clippy 1.84 lint

---

device/src/u3v/device_builder.rs
device/src/u3v/protocol/ack.rs
impl/src/memory.rs

Adds some parentheses for clarity
Using `cargo clippy --fix --all-targets --all-features` - fully automatic.
None

Fix clippy 1.85 lints
