cameleon-rs/cameleon

cameleon/src/u3v/control_handle.rs, device/src/u3v/protocol/cmd.rs
Fix #94 
* [cameleon-device] Add `ReadMem::maximum_read_length`
* [cameleon] Change u3v `read` strategy to eagerly read register with maximum length as long as possible
* [cameleon] Properly align `leader` and `trailer` size
=> Eagerly read u3v device register with maximum length when possible

genapi/src/command.rs
Remove unnecessary dependency on `command_value` in `is_writable` of command node
=> Remove unnecessary dependency on `command_value` in `is_writable` of command node

cameleon/src/genapi/mod.rs, cameleon/src/genapi/node_kind.rs, cameleon/src/lib.rs, genapi/src/builder.rs, genapi/src/enumeration.rs, genapi/src/interface.rs, genapi/src/parser/converter.rs, genapi/src/parser/elem_name.rs, genapi/src/parser/enumeration.rs, genapi/src/parser/node.rs, genapi/src/parser/port.rs, genapi/src/parser/string.rs, genapi/src/store.rs, genapi/src/utils.rs
fixes  #99 
* [cameleon-genapi] Make `EnumEntryNode` have `NodeId` as other nodes
* Change `EnumerationNode::entries` to return `&[NodeId]`
* `EnumerationNode::set_entry_by_name` -> `EnumerationNode::set_entry_by_symbolic`
* `EnumerationNode::entry_by_name` -> `EnumerationNode::entry_by_symbolic`
* Add `Node::as_enum_entry_node`
* Remove `IEnumerationKind::entries_precise`
* [cameleon] Add `EnumEntryNode`
* Change `EnumerationNode::entries` to return `Vec<EnumerationNode>`
* Change `EnumEntryNode::current_entry` to return `EnumerationNode`
=> Store `EnumEntryNode` to `NodeStore` in the same way like other nodes

cameleon/Cargo.toml, cameleon/src/u3v/mod.rs, cameleon/src/u3v/stream_handle.rs, device/Cargo.toml, device/src/u3v/async_read.rs, device/src/u3v/channel.rs, device/src/u3v/device.rs, device/src/u3v/device_builder.rs, device/src/u3v/mod.rs
Add support for `WinUSB`.
ref #104 
* [cameleon-device] Fix bugs related to `WinUSB`
* [cameleon-device] Make fields of `ControlChannel`  and `ReceiveChanel` private
=> Add support for `WinUSB`

cameleon/src/camera.rs, cameleon/src/genapi/mod.rs, cameleon/src/lib.rs, device/src/u3v/protocol/cmd.rs, genapi/src/elem_type.rs, genapi/src/lib.rs
Libraries like `anyhow` require wrapped errors to be Send and Sync, so this is hopefully a reasonable requirement.
We've faced this limitation when we wanted to wrap `CameleonError` in our application.
Note that this changes the public API of `cameleon_genapi::Device`.
CC @bschwind.
- `camelon::CameleonError` and all other public errors in the `cameleon` suite are now `Send` + `Sync`.
- `cameleon_genapi::Device` trait API has changed. Errors returned from its methods now must also implement `Send` + `Sync`.
=> Make `CameleonError` (thus all other errors) `Send` + `Sync`

device/src/u3v/protocol/ack.rs, device/src/u3v/protocol/cmd.rs, genapi/src/node_base.rs, genapi/src/parser/node_base.rs, genapi/src/parser/register_base.rs, impl/macros/src/register_map.rs
Fix #138 
When the GenICam XML follows schema version 1.1, non-register type nodes can have a `pInvalidator` element, though `cameleon` doesn't use the feature if it's a non-register type.
So this fix simply changes to include `pInvalidator` elements in `NodeElementBase`. I ensured this change was compatible with XML schema version 1.0.
@bschwind 
Could you test that this PR fixes the problem on your camera, please?
[cameleon-genapi] Fix a panic when non-register type nodes have `pInvalidator` element
=> Fix genicam parser

cameleon/src/u3v/control_handle.rs
During testing, we noticed if a process is shut down non-gracefully (for example, SIGKILL) while the camera is streaming, subsequent runs of the program fail because calls to `enable_streaming` fail.
We were able to fix this by checking if the stream is enabled, disabling it if it _is_ streaming, and then continue on enabling the stream as normal.
We ran `test_all.sh` on `main` and the following failed:
```
test src/camera.rs - camera::Camera<Ctrl,Strm,Ctxt>::params_ctxt (line 378) ... FAILED
test src/genapi/mod.rs - genapi (line 8) ... FAILED
test src/genapi/mod.rs - genapi::ParamsCtxt (line 67) ... FAILED
```
These same tests failed on our branch.
We also had to run the test with `RUST_TEST_THREADS=1` because we were getting a few `ControlError(busy)` errors. Rust runs tests in parallel …
=> Disable the camera stream before enabling it

.cargo/config, cameleon/src/camera.rs, cameleon/src/genapi/mod.rs
Ref: `Note` section in #147's PR comment. 
I decided to restrict the number of test threads to one for now so that multiple threads don't open the same camera simultaneously. I don't think this will decrease testing speed so much because there are not so many tests in the library. I'll refine the testing configuration if the testing performance becomes problematic.
None
=> Limit test thread

cameleon/src/u3v/register_map.rs, cameleon/src/u3v/stream_handle.rs, device/src/u3v/protocol/ack.rs, genapi/src/masked_int_reg.rs, impl/tests/macros/wrong_init_array.stderr
- ~Add `fix #{ISSUE_NUMBER}` if the corresponding issue exists.~
None
=> Fix clippy warnings (casting to the same type)

cameleon/Cargo.toml, cameleon/src/u3v/stream_handle.rs
The only use of the (cancellation, completion) channel pair is to synchronize teardown of streaming (either explicitly or when StreamHandle is dropped). This is also the only place where we were spinning and async runtime.
Turns out [`std::sync::mpsc::sync_channel(0)`](https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html) is as special "rendezvous" mode that should do what we want: sends a message and waits for it to be picked up. We also continue to detect StreamHandle drop from the streaming loop.
Should be functionally equivalent, just with less dependencies and without async runtime.
Needs testing.
None
=> Use std::mpsc rendezvous channel instead of pair of futures::channels

README.md, cameleon/Cargo.toml, cameleon/README.md, cameleon/examples/stream.rs, cameleon/src/payload.rs, device/Cargo.toml
Allows callers to wait for a frame without using futures. Turned out [async_channel::Receiver](https://docs.rs/async-channel/latest/async_channel/struct.Receiver.html) already had a [`recv_blocking()`](https://docs.rs/async-channel/latest/async_channel/struct.Receiver.html#method.recv_blocking) method, so this is rather straightforward.
In addition to the API changes, update READMEs and example to use the new method. The version in current `main` does a busy loop (consumes 100% of its CPU thread).
Best viewed with whitespace change ignored.
This is yet to be tested with a real camera (:pray: :pray: @bschwind).
- ~Add `fix #{ISSUE_NUMBER}` if the corresponding issue exists.~
- `recv_blocking()` method was introduced on `PayloadReceiver`. It allows callers to wait for a frame without using …
=> Introduce `recv_blocking()` method on `PayloadReceiver`

cameleon/Cargo.toml, cameleon/src/payload.rs, device/src/emulator/emulator_impl/memory_event_handler.rs
Together with #157 this makes cameleon's dependencies much leaner.
Also fixes the minor issue that we previously didn't enforce async-channel version that contained recv_blocking().
None
=> Narrow down async-std dependency to async-channel

README.md
Just testing if pushes directly to `main` are allowed (for pushing the version bump for release), this is hopefully uncontroversial enough that it can stay if it gets through.
Okay these are not allowed, so I'm submitting as a PR now I've made the change. :)
None
=> README: remove a note about regular releases

cameleon/Cargo.toml, device/Cargo.toml, genapi/Cargo.toml, gentl/Cargo.toml, impl/Cargo.toml, impl/macros/Cargo.toml
Prep for a release.
100% made by `cargo release version patch`.
=> Bump versions to 0.1.9

Cargo.toml
Closes #159 (I'll cut the release right after merging this).
I'll go ahead and ista-merge this, it just reflects discussion in #159.
=> Configure `cargo-release` to use single tag for all crates

cameleon/src/u3v/stream_handle.rs
This likely doesn't fix much, but I noticed the use of trailer and leader buffers was swapped. In my testing, the leader and trailer buffers were reported by the camera device to be the same size, which lets this "bug" slip by without causing an issue, but perhaps other cameras have different leader and trailer sizes.
None
=> Fix swapped use of leader and trailer buffers

device/src/u3v/async_read.rs
The `AsyncTransfer` struct was leaking an `AtomicBool`, as it was converted to a raw pointer but never converted back. We found this by using a memory sanitizer (heaptrack) and verified that everything is healthy after the fix.
We have the suspicion that this may fix some unrelated FPS drop issue we've experienced, but we haven't yet verified that. 
Fixes tonarino/portal#2283 (tonari's internal issue tracking the mem leak).
None
=> Fix memory leak on `AsyncTransfer` struct

cameleon/src/lib.rs, cameleon/src/u3v/stream_handle.rs
Fixes #156
This changes the U3V capture loop to use async bulk transfers for the leader and trailer buffers, as well as the payload buffers.
Async was already used for the payload buffers, but the leader and trailer buffers were read synchronously. My guess is the synchronous read of a leader buffer caused the camera we were testing in #156 to start sending data, and with the synchronous nature of bulk transfers, our timing may have been delayed which lead to `DataDiscarded` errors when reading the actual frame payloads.
With this change, we queue up _all_ bulk transfers at once so the bus is continuously able to transfer data without having to wait for our code to issue more reads. This should result in a more stable operation, possibly lower latency, and possibly the capability to …
=> Use async USB bulk transfers for leader and trailer buffers

device/src/u3v/async_read.rs, genapi/src/boolean.rs, genapi/src/command.rs, genapi/src/elem_type.rs, genapi/src/enumeration.rs, genapi/src/float.rs, genapi/src/integer.rs, genapi/src/ivalue.rs, genapi/src/store.rs
This change allows an implicit casting between int, float, and enum types when the GenApi context requires this kind of casting. 
NOTE: This change doesn't affect the public API.
=> Allow implicit cast between (GenICam) int, float, and enum

genapi/src/port.rs
BTW the `rustflags = ["-D", "warnings"]` in https://github.com/cameleon-rs/cameleon/blob/main/.cargo/config might a bit too strict: it prevents from compiling code with warnings during development iterations.
More canonical would be to do a following change to https://github.com/cameleon-rs/cameleon/blob/main/.github/workflows/ci.yml:
```diff
-        run: cargo clippy --workspace --all-targets --all-features -- -D clippy::all
+        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
```
(which catches both rustc and clippy warnings)
None
=> Fix clippy 1.73 lints (trivial)

.cargo/config, .github/workflows/ci.yml, test_all.sh
This PR weakens lint-deny-level to reduce troublesomeness in a development process, which was pointed out [here](https://github.com/cameleon-rs/cameleon/pull/172#issue-1952083470).
None
=> Weaken lint-deny-level(trivial)

device/src/u3v/async_read.rs, gentl/src/ffi/port.rs
- ~Add `fix #{ISSUE_NUMBER}` if the corresponding issue exists.~
None
=> Fix clippy 1.75 warnings

genapi/src/register_base.rs
Function parameters were out of order
Bugfix in register_base.rs::with_cache_or_read: Function parameters were out of order.
=> Bugfix in register_base.rs

cameleon/src/u3v/control_handle.rs, genapi/src/masked_int_reg.rs, genapi/src/parser/elem_type.rs, genapi/src/parser/port.rs, genapi/src/parser/string.rs, genapi/src/store.rs
```
test examples/u3v/register_map.rs ... error
Test case failed at runtime.
STDERR:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
warning: `/home/strohel/work/cameleon/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
thread 'main' panicked at library/core/src/panicking.rs:220:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_nounwind_fmt
2: core::panicking::panic_nounwind
3: core::slice::raw::from_raw_parts::precondition_check
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ub_ch …
```
=> Fix lints introduced by clippy 1.78 to 1.80

device/Cargo.toml, device/src/u3v/device_builder.rs
- on top of https://github.com/cameleon-rs/cameleon/pull/188 which should be merged first
...which fixes a panic in dev builds / undefined behavior in release builds: https://github.com/a1ien/rusb/pull/195
See https://github.com/cameleon-rs/cameleon/pull/188#issuecomment-2296597805 and above.
- Prevent a panic/undefined behavior in rusb (https://github.com/a1ien/rusb/pull/195) by allowing its newest 0.9.4 version by bumping libusb1-sys
=> Bump libusb1-sys to allow newest rusb

README.md
Sorry for squashing loosely related changes to a single PR.
The release docs are based on https://github.com/cameleon-rs/cameleon/issues/159#issuecomment-1473919709 but tweaked
=> Update README: add maintained badge, release procedure

genapi/src/elem_type.rs, genapi/src/parser/integer.rs
Bugfix: The **product** of _Offset_ and _Index_ need to be added to the address for address offset calculations.
Bugfix: Default increment for Integer Nodes is 1.
=> Offset calculation is multiplicative in GenICam + Default for increment in Integer Nodes

cameleon/Cargo.toml, device/Cargo.toml, genapi/Cargo.toml, gentl/Cargo.toml, impl/Cargo.toml, impl/macros/Cargo.toml
This PR bumps up the version to `0.1.14` from `0.1.13`.
=> Bump version to `0.1.14`
